name: Build

on:
  push:
    branches: ['**']
    tags: ['[0-9]*']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    permissions:
      contents: write
    steps:
      - name: Install distro deps
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S base-devel python git vim nasm dosfstools mtools xorriso

      - name: Mark workspace safe for git
        run: git config --global --add safe.directory '*'

      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0
          fetch-tags: true

      - name: make x86_64
        run: |
          make ARCH=x86_64
          mkdir -p bin
          cp bin-x86_64/csmwrap.efi bin/csmwrapx64.efi

      - name: make ia32
        run: |
          make ARCH=ia32
          mkdir -p bin
          cp bin-ia32/csmwrap.efi bin/csmwrapia32.efi

      - name: generate iso
        run: |
          mkdir -p iso/EFI/Boot
          ln bin/csmwrapx64.efi iso/EFI/Boot/BOOTx64.EFI
          ln bin/csmwrapia32.efi iso/EFI/Boot/BOOTIA32.EFI
          fallocate -l 2M iso/efi.img
          mkfs.fat -F12 -a -b0 -f1 -r16 -R1 iso/efi.img
          mcopy -si iso/efi.img iso/EFI ::
          rm -rf iso/EFI
          xorriso -as mkisofs -V "CSMWRAP" -e "efi.img" -no-emul-boot \
          -isohybrid-gpt-basdat -part_like_isohybrid -o bin/csmwrap.iso iso

      - uses: actions/upload-artifact@v7
        with:
          name: csmwrap.efi
          path: bin/*.efi

      - name: Create draft release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            bin/csmwrapx64.efi
            bin/csmwrapia32.efi
            bin/csmwrap.iso
